---
kind: pipeline
type: docker
name: compile-x64

clone:
  disable: true

steps:
- name: compile-x64
  image: ubuntu:latest
  commands:
  - apt update && apt upgrade -y && apt install -y cmake g++ gcc git make
  - git clone $DRONE_REMOTE_URL .
  - git checkout $DRONE_COMMIT
  - git submodule update --init --recursive
  - mkdir build-x64 && cd build-x64 && cmake .. -DDOWNLOAD_CURL=ON -DDOWNLOAD_SODIUM=ON && make && make check

---
kind: pipeline
type: docker
name: compile-aarch64

clone:
  disable: true

steps:
- name: compile-aarch64
  image: ubuntu:latest
  commands:
  - apt update && apt upgrade -y && apt install -y cmake make git g++-aarch64-linux-gnu gcc-aarch64-linux-gnu
  - git clone $DRONE_REMOTE_URL .
  - git checkout $DRONE_COMMIT
  - git submodule update --init --recursive
  - mkdir build-aarch64 && cd build-aarch64 && cmake .. -DNATIVE_BUILD=OFF -DCROSS_TARGET=aarch64-linux-gnu -DDOWNLOAD_CURL=ON -DDOWNLOAD_SODIUM=ON -DCMAKE_TOOLCHAIN_FILE=../contrib/cross/aarch64.toolchain.cmake && make
